### ISSUE TITLE
rbenv plugin work

### ISSUE THREAD

**Issue by ysolis** [maljub01/rbenv-bundle-exec#3] opened 2015-01-08 15:08 UTC
I am reinstalling my rbenv now, all works, but i leave the rbev-bundler pliugin outside.

right now i am testing https://github.com/maljub01/rbenv-bundle-exec and works very well with me.

Ubuntu 14.04
zsh with oh-my-zsh, bundler, and rbenv plugin now installed.

this one works very well, with me, without need for "bundle exec" (i have a 'be' alias in zsh that works very well in any case too)

this plugin have any problem with rbenv core ? i would like to work in this too (if is needed)

**Comment by maljub01** [comment] 2015-01-10 17:55
Thank you for submitting this. I do not yet know of any issues that might be caused by rbenv-bundle-exec.

In sstephenson/rbenv#677, I saw that you mentioned that you ended up facing some issues with your setup. If you believe rbenv-bundle-exec has been causing any problems, I would love to know what those problems are in order to help resolve them if possible.

Thanks :+1:

**Comment by ysolis** [comment] 2015-01-12 20:16
maybe you need to expose differences between rbenv-bundle-exec and rbenv-bundler for example.

rbenv-bundler add more shims based in your Gemfile, unrelated to this, for example if your Gemfile have rails 4, erubis will get installed, but in rbenv-bundler one shims called erubis wll get created. in rbenv-bundler-exec no, and this difference will need to be documented.

**Comment by maljub01** [comment] 2015-01-14 22:52
I agree. I always thought that I am not doing a very good job documenting this plugin, or writing the README.md which is all the documentation there is so far anyway. I currently try to explain the difference between this and other bundler-integration plugins under the [similar plugins section](https://github.com/maljub01/rbenv-bundle-exec#similar-plugins) in the README.

If I understood your point correctly, rbenv-bundler has a bug in dealing with running gem dependencies that are not explicitly mentioned in the Gemfile. Do you know if this is a bug with the latest version of rbenv-bundler? A quick look at the project shows that this is something that's been resolved in an earlier release and there are currently no open issues.

**Closed as completed** 2015-05-06 18:08 UTC
